#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    registerWithEureka: true
#    fetchRegistryWithEureka: true
#    service-url:
#      defaultZone: http://localhost:8070/eureka
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/football_db?autoReconnect=true&useSSL=false
#    username: postgres
#    password: marisfelipe1805
#    driver-class-name: org.postgresql.Driver


management.endpoints.web.exposure.include=*
management.endpoints.enabled-by-default=true

eureka.instance.preferIpAddress = true
eureka.client.registerWithEureka = true
eureka.client.fetchRegistry = true
eureka.client.serviceUrl.defaultZone = http://localhost:8070/eureka/