server:
  port: 8081

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistryWithEureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka