server:
  port: 8082

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistryWithEureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/football_db?autoReconnect=true&useSSL=false
    username: postgres
    password: marisfelipe1805
    driver-class-name: org.postgresql.Driver